### ISSUE TITLE
dothereum developer/contributor call #0

### ISSUE THREAD

**Issue by soc1c** [dothereum/coordination#1]
### dothereum developer/contributor call 0

first public dothereum developer and contributor call to kick of the public blockchain launch efforts. please join if you are familiar with or want to learn about dothereum, and eventually want to contribute. http://dothereum.net/

Date / Time
- Wednesday, November 13th, 2018
- [9am UTC](https://savvytime.com/converter/ca-san-francisco-to-canada-toronto-utc-germany-berlin-china-shanghai-russia-vladivostok-japan-osaka-shi)

### Agenda
- Public Project kick-off
- Team intros
  - Core team
  - Contributors
- Initial Roadmapping and Wrapping
  - Dothereum Alpha testnet recap
  - Dothereum Gamma testnet preparations
- Tooling and external resources
  - Public Gamma Websocket
  - Polkadot-JS integration
  - Polkascan integration
- _Please add your items_

cc @arsenyjin @orca84

**Comment by roninkaizen** [comment]
read and understood,
not sure if i can join, but <-- contributor

**Comment by soc1c** [comment]
Starting in 5

Meeting URL: https://meet.google.com/dax-wdid-jiv
Phone: +49 30 300195119 PIN: 969 679 273 14#
More numbers: https://t.meet/dax-wdid-jiv

**Comment by soc1c** [comment]
Notes: https://github.com/dothereum/coordination/blob/master/2019-11-13-devcall-0.md

Next Call: #2 on Nov/27 2019
